# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMovies' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'MBProgressHUD'
  pod 'Kingfisher', '~> 4.7.0'
  pod 'SwiftMessages', '4.1.4'
end
